device:
  name: pyri_robotics_motion_service
manufacturer:
  name: PyRI_Project
  uuid: 244389f3-35d5-4f9f-a244-c89649ce2a18
model:
  name: pyri_robotics_motion_service
  uuid: 06c2fde2-0b9d-48c7-a509-eee54a417c82
user_description: Robotics motion controller service
serial_number: 1
device_classes:
  - class_identifier:
      name: pyri_robotics
      uuid: cc6da689-a9e0-48e1-9020-1b247514e229
    subclasses:
      - robotics_motion
implemented_types:
  - com.robotraconteur.device.Device
  - tech.pyri.robotics.motion.RoboticsMotionService