device:
  name: pyri_jog_joint_service
manufacturer:
  name: PyRI_Project
  uuid: 244389f3-35d5-4f9f-a244-c89649ce2a18
model:
  name: pyri_jog_joint
  uuid: 603a13c1-1eb3-426b-a964-012bda3ba50b
user_description: Joint jog controller service
serial_number: 1
device_classes:
  - class_identifier:
      name: joint_jog
      uuid: edc79305-f9df-4089-98c4-7979858122dd
    subclasses:
      - joint_jog
implemented_types:
  - com.robotraconteur.device.Device
  - tech.pyri.robotics.pluginJogJointSpace